[package]
name = "akmux-desktop-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
akmux-client-core.workspace = true
async-channel.workspace = true
gpui.workspace = true
keyring.workspace = true
serde.workspace = true
thiserror.workspace = true
tray-icon.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
gtk.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys.workspace = true
