[package]
name = "akmux-terminal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
akmux-client-core.workspace = true
alacritty_terminal.workspace = true
async-channel.workspace = true
gpui.workspace = true
parking_lot.workspace = true
serde.workspace = true
sha2.workspace = true
tokio.workspace = true
